api = "0.7"

[buildpack]
description = "A buildpack for precompiling rails assets"
homepage = "https://github.com/paketo-buildpacks/rails-assets"
id = "neeto-deploy/rails-assets"
keywords = ["ruby", "rails", "assets"]
name = "Paketo Buildpack for Rails Assets"
version = "0.10.27"

[[buildpack.licenses]]
type = "Apache-2.0"
uri = "https://github.com/paketo-buildpacks/rails-assets/blob/main/LICENSE"

[metadata]
include-files = [
  "buildpack.toml",
  "linux/amd64/bin/build",
  "linux/amd64/bin/detect",
  "linux/amd64/bin/run",
  "linux/arm64/bin/build",
  "linux/arm64/bin/detect",
  "linux/arm64/bin/run",
]

pre-package = "./scripts/build.sh"

[[stacks]]
id = "*"

[[targets]]
os = "linux"
arch = "amd64"

[[targets]]
os = "linux"
arch = "arm64"
